export const studentPortalData = {
	_id: 1,
	firstName: 'BALOEES',
	lastName: 'SABIR',
	registeredCourses: [
		{
			id: 1,
			name: 'Introduction to React js',
			dateStart: '2023-08-07',
			lessons: 12,
			level: 1,
			image: '',
			status: 'ongoing',
			enrolledStudents: 20,
			Instructor: {
				firstName: 'TARIQ',
				lastName: 'Ali',
			},
		},
		{
			id: 2,
			name: 'Introduction to JavaScript',
			dateStart: '2023-09-01',
			lessons: 14,
			level: 1,
			image: '',
			status: 'ongoing',
			enrolledStudents: 25,
			Instructor: {
				firstName: 'Sara',
				lastName: 'Ahmed',
			},
		},
		{
			id: 3,
			name: 'Introduction to React js',
			dateStart: '2023-08-07',
			lessons: 12,
			level: 1,
			image: '',
			status: 'upcoming',
			enrolledStudents: 15,
			Instructor: {
				firstName: 'TARIQ',
				lastName: 'Ali',
			},
		},
		{
			id: 4,
			name: 'Introduction to JavaScript',
			dateStart: '2023-09-01',
			lessons: 14,
			level: 1,
			image: '',
			status: 'upcoming',
			enrolledStudents: 12,
			Instructor: {
				firstName: 'Sara',
				lastName: 'Ahmed',
			},
		},
		{
			id: 5,
			name: 'Introduction to React js',
			dateStart: '2023-08-07',
			lessons: 12,
			level: 1,
			image: '',
			status: 'ended',
			enrolledStudents: 20,
			Instructor: {
				firstName: 'TARIQ',
				lastName: 'Ali',
			},
		},
		{
			id: 6,
			name: 'Introduction to JavaScript',
			dateStart: '2023-09-01',
			lessons: 14,
			level: 1,
			image: '',
			status: 'ended',
			enrolledStudents: 10,
			Instructor: {
				firstName: 'Sara',
				lastName: 'Ahmed',
			},
		},
		{
			id: 7,
			name: 'Introduction to React js',
			dateStart: '2023-08-07',
			lessons: 12,
			level: 1,
			image: '',
			status: 'ended',
			enrolledStudents: 8,
			Instructor: {
				firstName: 'TARIQ',
				lastName: 'Ali',
			},
		},
		{
			id: 8,
			name: 'Introduction to JavaScript',
			dateStart: '2023-09-01',
			lessons: 14,
			level: 1,
			image: '',
			status: 'ended',
			enrolledStudents: 24,
			Instructor: {
				firstName: 'TARIQ',
				lastName: 'Ali',
			},
		},
	],

	exams: [
		{
			_id: 1,
			name: 'Introduction to React js',
			Instructor: 'Tariq Ali',
			level: 1,
			date: '2023-12-30',
			time: '12:30 PM',
		},
		{
			_id: 2,
			name: 'Introduction to JavaScript',
			Instructor: 'Sara Ahmed',
			level: 1,
			date: '2023-12-12',
		},
	],

	earnedCertificates: [
		{
			_id: 1,
			name: 'Introduction to React js',
			Instructor: { firstName: 'Tariq', lastName: 'Ali' },
			earnedDate: '2023-06-05',
			link: '#',
		},
	],
};

export const instructorPortalData = {
	_id: 1,
	firstName: 'BALOEES',
	lastName: 'SABIR',
	todayExam: false,
	registeredCourses: [
		{
			id: 1,
			name: 'Introduction to React js',
			dateStart: '2023-08-07',
			lessons: 12,
			level: 1,
			image: '',
			status: 'ongoing',
			enrolledStudents: 20,
		},
		{
			id: 2,
			name: 'Introduction to JavaScript',
			dateStart: '2023-09-01',
			lessons: 14,
			level: 1,
			image: '',
			status: 'ongoing',
			enrolledStudents: 25,
		},
		{
			id: 3,
			name: 'Introduction to React js',
			dateStart: '2023-08-07',
			lessons: 12,
			level: 1,
			image: '',
			status: 'upcoming',
			enrolledStudents: 15,
		},
		{
			id: 4,
			name: 'Introduction to JavaScript',
			dateStart: '2023-09-01',
			lessons: 14,
			level: 1,
			image: '',
			status: 'upcoming',
			enrolledStudents: 12,
		},
		{
			id: 5,
			name: 'Introduction to React js',
			dateStart: '2023-08-07',
			lessons: 12,
			level: 1,
			image: '',
			status: 'ended',
			enrolledStudents: 20,
		},
		{
			id: 6,
			name: 'Introduction to JavaScript',
			dateStart: '2023-09-01',
			lessons: 14,
			level: 1,
			image: '',
			status: 'ended',
			enrolledStudents: 10,
		},
		{
			id: 7,
			name: 'Introduction to React js',
			dateStart: '2023-08-07',
			lessons: 12,
			level: 1,
			image: '',
			status: 'ended',
			enrolledStudents: 8,
		},
		{
			id: 8,
			name: 'Introduction to JavaScript',
			dateStart: '2023-09-01',
			lessons: 14,
			level: 1,
			image: '',
			status: 'ended',
			enrolledStudents: 24,
		},
	],

	exams: [
		{
			_id: 1,
			name: 'Introduction to React js',
			Instructor: 'Tariq Ali',
			level: 1,
			date: '2023-12-30',
			time: '12:30 PM',
		},
		{
			_id: 2,
			name: 'Introduction to JavaScript',
			Instructor: 'Sara Ahmed',
			level: 1,
			date: '2023-12-12',
		},
	],
};
